[build]
  command = "npm install && npm run build"  # Ensures dependencies are installed before building
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  framework = "vite"  # Explicitly specifying Vite if you are using it

# Ensure client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache optimizations (optional)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-cache"

