[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080

# Ensure client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 